version: "3.8"

services:

  django_gunicorn:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - static:/static
    ports:
      - "8000:8000"
    container_name: django_app_container
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env

  db:
    restart: always
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    container_name: postgres_db
    env_file:
      - .env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  nginx:
    image: nginx:latest
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - static:/static
    ports:
      - "80:8000"
    container_name: nginx_container
    depends_on:
      - django_gunicorn

volumes:
  static: