version: "3.8"

services:

  django_gunicorn:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - static:/static
    ports:
      - "8000:8000"
    container_name: django_app_container
    depends_on:
      - db
    env_file:
      - backend/.env

  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    container_name: postgres_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}

  nginx:
    build: ./nginx
    volumes:
      - static:/static
    ports:
      - "80:8000"
    depends_on:
      - django_gunicorn
    container_name: nginx_container

volumes:
  static: