# Generated by Django 4.2.2 on 2023-06-25 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Title')),
                ('bought', models.IntegerField(default=0, help_text='The price is the value divided by 100 (848 = 8,48 $)', verbose_name='Bought')),
                ('sold', models.IntegerField(blank=True, help_text='902 = 9,02 $', verbose_name='Sold')),
                ('profit', models.IntegerField(blank=True, help_text='54 = 0,54 $', verbose_name='Profit')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Date of creation')),
                ('closed_at', models.DateTimeField(blank=True, verbose_name='Closing date')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounting.category', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Tickets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='Operation',
        ),
    ]
