# Generated by Django 4.2.2 on 2023-06-25 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_alter_ticket_profit_alter_ticket_sold'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='closed',
            field=models.CharField(choices=[(False, 'No'), (True, 'Yes')], default=0, max_length=100, verbose_name='Closed'),
            preserve_default=False,
        ),
    ]
