# Generated by Django 4.2.2 on 2023-07-02 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0012_alter_ticket_bought_alter_ticket_profit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='bought',
            field=models.FloatField(default=0, verbose_name='Bought'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='profit',
            field=models.FloatField(blank=True, null=True, verbose_name='Profit'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='sold',
            field=models.FloatField(blank=True, null=True, verbose_name='Sold'),
        ),
    ]
