# Generated by Django 4.2.2 on 2023-07-04 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0013_alter_ticket_bought_alter_ticket_profit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='deleted',
            field=models.CharField(choices=[('False', 'No'), ('True', 'Yes')], default='False', max_length=100, verbose_name='Closed'),
        ),
    ]
