# Generated by Django 4.2.2 on 2023-07-04 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0014_ticket_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='deleted',
            field=models.CharField(choices=[('False', 'No'), ('True', 'Yes')], default='False', max_length=100, verbose_name='Deleted'),
        ),
    ]
