# Generated by Django 4.2.2 on 2023-07-08 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0015_alter_ticket_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Title')),
                ('query_request', models.CharField(max_length=150, verbose_name='Annotation')),
                ('annotation', models.CharField(max_length=150, verbose_name='Annotation')),
                ('color', models.CharField(max_length=150, verbose_name='Color')),
            ],
        ),
    ]
