# Generated by Django 4.2.2 on 2023-07-08 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0016_ticketfilter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketfilter',
            name='query_request',
        ),
        migrations.AddField(
            model_name='ticketfilter',
            name='query_value',
            field=models.CharField(default=0, max_length=150, verbose_name='Query'),
            preserve_default=False,
        ),
    ]
