# Generated by Django 4.2.2 on 2023-07-09 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0017_remove_ticketfilter_query_request_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketfilter',
            name='url_value',
            field=models.CharField(default=0, max_length=150, verbose_name='URL'),
            preserve_default=False,
        ),
    ]
