# Generated by Django 4.2.2 on 2024-05-20 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0019_alter_ticketfilter_query_value'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TicketFilter',
        ),
    ]
