# Generated by Django 4.2.2 on 2023-07-02 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserAdditional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paginate_by', models.CharField(choices=[('10', '10'), ('15', '15'), ('25', '25'), ('50', '50'), ('100', '100')], default='10', max_length=50, verbose_name='Pagination')),
            ],
            options={
                'verbose_name': 'Additional User Settings',
                'verbose_name_plural': 'Additional User Settings',
            },
        ),
    ]
