# Generated by Django 4.2.2 on 2023-07-06 20:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useradditional',
            name='all_time_profit',
            field=models.FloatField(default=0, verbose_name='Profit'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='useradditional',
            name='highest_loss',
            field=models.FloatField(default=0, verbose_name='Highest loss'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='useradditional',
            name='highest_profit',
            field=models.FloatField(default=0, verbose_name='Highest profit'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='useradditional',
            name='tickets_quantity',
            field=models.IntegerField(default=0, verbose_name='Quantity'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='useradditional',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='user_additional', to=settings.AUTH_USER_MODEL, verbose_name='User'),
            preserve_default=False,
        ),
    ]
