# Generated by Django 4.2.2 on 2023-07-07 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_useradditional_all_time_profit_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useradditional',
            options={'ordering': ['user'], 'verbose_name': 'Additional User Settings', 'verbose_name_plural': 'Additional User Settings'},
        ),
        migrations.AlterField(
            model_name='useradditional',
            name='all_time_profit',
            field=models.FloatField(default=0, verbose_name='Profit'),
        ),
        migrations.AlterField(
            model_name='useradditional',
            name='highest_loss',
            field=models.FloatField(default=0, verbose_name='Highest loss'),
        ),
        migrations.AlterField(
            model_name='useradditional',
            name='highest_profit',
            field=models.FloatField(default=0, verbose_name='Highest profit'),
        ),
        migrations.AlterField(
            model_name='useradditional',
            name='tickets_quantity',
            field=models.IntegerField(default=0, verbose_name='Quantity'),
        ),
    ]
