# Generated by Django 4.2.2 on 2023-07-10 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_useradditional_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useradditional',
            name='currency',
            field=models.CharField(choices=[('USD', '$'), ('EUR', '€'), ('RUB', '₽'), ('UAH', '₴'), ('MDL', 'L')], default='USD', max_length=50, verbose_name='Currency'),
        ),
        migrations.AddField(
            model_name='useradditional',
            name='display_symbol',
            field=models.BooleanField(default=False, verbose_name='Display symbol'),
        ),
    ]
