# Generated by Django 4.2.2 on 2023-07-10 20:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0004_useradditional_currency_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useradditional',
            options={},
        ),
        migrations.RemoveField(
            model_name='useradditional',
            name='all_time_profit',
        ),
        migrations.RemoveField(
            model_name='useradditional',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='useradditional',
            name='display_symbol',
        ),
        migrations.RemoveField(
            model_name='useradditional',
            name='highest_loss',
        ),
        migrations.RemoveField(
            model_name='useradditional',
            name='highest_profit',
        ),
        migrations.RemoveField(
            model_name='useradditional',
            name='paginate_by',
        ),
        migrations.RemoveField(
            model_name='useradditional',
            name='tickets_quantity',
        ),
        migrations.RemoveField(
            model_name='useradditional',
            name='user',
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paginate_by', models.CharField(choices=[('5', '5'), ('10', '10'), ('15', '15'), ('25', '25'), ('50', '50'), ('100', '100'), ('200', '200')], default='10', max_length=50, verbose_name='Pagination')),
                ('currency', models.CharField(choices=[('$', '$'), ('€', '€'), ('₽', '₽'), ('₴', '₴'), ('L', 'L')], default='$', max_length=50, verbose_name='Currency')),
                ('display_symbol', models.BooleanField(default=False, verbose_name='Display symbol')),
                ('delete_confirmation', models.BooleanField(default=True, verbose_name='Delete confirmation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_settings', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'User Settings',
                'verbose_name_plural': 'User Settings',
                'ordering': ['user'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('all_time_profit', models.FloatField(default=0, verbose_name='Profit')),
                ('tickets_quantity', models.IntegerField(default=0, verbose_name='Quantity')),
                ('highest_profit', models.FloatField(default=0, verbose_name='Highest profit')),
                ('highest_loss', models.FloatField(default=0, verbose_name='Highest loss')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_profile', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profile',
                'ordering': ['user'],
            },
        ),
    ]
