# Generated by Django 4.2.2 on 2023-07-10 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_useradditional_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserAdditional',
        ),
    ]
