# Generated by Django 4.2.2 on 2023-07-11 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_delete_useradditional'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommandCurrency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=10, verbose_name='Currency')),
            ],
        ),
        migrations.CreateModel(
            name='CommandPagination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paginate_by', models.IntegerField(verbose_name='Paginate By')),
            ],
        ),
    ]
