# Generated by Django 4.2.2 on 2023-07-12 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_usersettings_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersettings',
            name='paginate_by',
            field=models.ForeignKey(default=10, max_length=50, on_delete=django.db.models.deletion.PROTECT, to='user.commandpagination', verbose_name='Pagination'),
        ),
    ]
