# Generated by Django 4.2.2 on 2023-07-14 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_alter_usersettings_paginate_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersettings',
            name='currency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='user.commandcurrency', verbose_name='Currency'),
        ),
    ]
