# Generated by Django 4.2.2 on 2023-07-14 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_alter_usersettings_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersettings',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.commandcurrency', verbose_name='Currency'),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='paginate_by',
            field=models.ForeignKey(default=10, max_length=50, on_delete=django.db.models.deletion.CASCADE, related_name='command_pagination', to='user.commandpagination', verbose_name='Pagination'),
        ),
    ]
