# Generated by Django 4.2.2 on 2023-07-14 15:38

from django.db import migrations, models
import django.db.models.deletion
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_alter_usersettings_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersettings',
            name='currency',
            field=models.ForeignKey(default=user.models.CommandCurrency.get_default_pk, on_delete=django.db.models.deletion.CASCADE, to='user.commandcurrency', verbose_name='Currency'),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='paginate_by',
            field=models.ForeignKey(default=user.models.CommandPagination.get_default_pk, max_length=50, on_delete=django.db.models.deletion.CASCADE, related_name='command_pagination', to='user.commandpagination', verbose_name='Pagination'),
        ),
    ]
